name: "Custom action"
description: "Just a custom action"
inputs:
  user:
    description: "id of user"
    required: true
output: 
  success: 
    description: "success of process"
    value: ${{ steps.results.outputs.result }}
runs: 
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.user }}
      shell: bash
    - id: results
      run: echo "::set-output name=result::1"
      shell: bash
    - run: echo "$GITHUB_ACTION_PATH"
      shell: bash
