name: Create release

on:
  workflow_dispatch:
    inputs:
      version_type:
        required: true
        description: Are you making a major version (a breaking change for consumers), minor one (new feature) or a patch (fix, documentation or technical enhancement) ?
        default: patch

env:
  NODE_VERSION_TARGET: '16'

jobs:

  deploy_bu1:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      bu: BU1
  deploy_bu2:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      bu: BU2
