name: Create release

on:
  workflow_dispatch:
    inputs:
      version_type:
        required: true
        description: Are you making a major version (a breaking change for consumers), minor one (new feature) or a patch (fix, documentation or technical enhancement) ?
        default: patch

env:
  NODE_VERSION_TARGET: '16'

jobs:

  send_release_results:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bu: [ 'BU1', 'BU2', 'BU3']
    steps:
      - uses: action/checkout@v3
      - uses: ./.github/workflows/reusable-workflow.yml
        with:
          bu: ${{ matrix.bu }}
