name: Create release

on:
  workflow_dispatch:
    inputs:
      version_type:
        required: true
        description: Are you making a major version (a breaking change for consumers), minor one (new feature) or a patch (fix, documentation or technical enhancement) ?
        default: patch
    branches: [ master ]

env:
  NODE_VERSION_TARGET: '16'

jobs:
  send_release_results:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bu: [ 'BU1', 'BU2', 'BU3']
    steps:
      - name: Repository Dispatch - Sending release results
        run: |
          curl \
            -X POST \
            -u ${{ secrets.REPO_ACCESS_USER }}:${{ secrets.REPO_ACCESS_TOKEN }} \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$GITHUB_REPOSITORY/dispatches \
            -d '{"event_type":"new-release_${{ matrix.bu }}", "client_payload": { "bu": "${{ matrix.bu }}" }}'
