name: Deploy

on:
  repository_dispatch:
    types: [ new-release_BU1, new-release_BU2, new-release_BU3 ]

env:
  NODE_VERSION_TARGET: '16'

jobs:
  custom_job:
    runs-on: ubuntu-latest

    env:
      SECRET_NAME: BU_${{ github.event.client_payload.bu }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION_TARGET }}
          cache: 'npm'
      - name: use custom action$
        uses: ./github/actions/test_action/
        with:
          user: $SECRET_NAME
      
