name: 🤖 Build and validate

on:
  push

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - run: echo "Start building ${{ github.ref }} from ${{ github.repository }} on ${{ runner.os }}"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm ci
      - name: Commit gherkin report
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Configuring git"
          git diff HEAD^..HEAD --name-only | grep .feature
          feature_updated=$?
          if [ "$feature_updated" -eq 0 ]
          then
            echo "Update report.html"
            git config --global user.email sebastien.gatineau@outlook.com
            git config --global user.name "Sébastien GATINEAU"
            echo "${{ runner.name }}" > report.html
            git add report.html
            git commit -m "chore(use-case): update gherkin report [skip ci]"
            git push origin main --no-verify
          else
            echo "no need to update gherkin report"
          fi



