name: Reusable workflow example

on:
  workflow_call:
    inputs:
      bu:
        required: true
        type: string
        
env:
  NODE_VERSION_TARGET: '16'

jobs:
  custom_job:
    runs-on: ubuntu-latest
    if: inputs.bu == 'BU1'
    steps:
      - uses: actions/checkout@v2
      - name: use custom action$
        uses: ./.github/actions/test_action/
        with:
          user: ${{ inputs.bu }}
  second_custom_job:
    needs: [custom_job]
    environment: 
      name: BU_${{inputs.bu}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: use custom action$
        uses: ./.github/actions/test_action/
        with:
          user: ${{ inputs.bu }}
        
